services:
  ambassador:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sentiment-app
    
  sentiment-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./prediction_logs:/app/prediction_logs
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    
  loggly-logger:
    image: garland/loggly
    volumes:
      - ./logs:/var/log/app_logs
      - ./prediction_logs:/var/log/prediction_logs
    environment:
      - LOGGLY_TOKEN=
      - LOGGLY_ACCOUNT=
      - USERNAME=
      - PASSWORD=
      - DIRECTORIES_TO_MONITOR=/var/log/app_logs,/var/log/prediction_logs
      - TAGS=sentiment-analysis
      - LOGS_WAIT_TIME=5
      - RETRY_ATTEMPTS=3
    restart: unless-stopped
    network_mode: "host"  # Try this to improve connectivity
    depends_on:
      - sentiment-app